# Generated by Django 5.1.1 on 2024-09-24 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
